#!/bin/bash
#
# SBATCH --job-name=ptv3-dítill
# SBATCH --nodes=1
# SBATCH --ntasks=1
# SBATCH --ntasks-per-node=1
# SBATCH --cpus-per-task=2
# SBATCH --gres=gpu:1
# SBATCH --mem=128G
# #SBATCH --partition=amperenodes
# SBATCH --partition=pascalnodes
# SBATCH --time=1:00:00
# SBATCH --output=terminal_logs/result_%j.txt
# SBATCH --error=terminal_logs/error_%j.txt
# SBATCH --mail-type=BEGIN,END,FAIL


### Loading the required CUDA and cuDNN modules
module load CUDA/11.8
module load cuDNN/8.9.3
module load python/3.8  # Adjust to the required version

### Loading the Anaconda module and activating the `tensorflow` environment
module load Anaconda3

python test_cheaha.py
